export type YKSType = "SAY" | "EA" | "SÖZ" | "DİL";

export interface TurkishUniversity {
  id: string;
  name: string;
  nameEn: string;
  city: string;
  type: "state" | "foundation";
  yksTypes: YKSType[];
  programs: string[];
  qsRank?: string;
  tuition: string;
  website: string;
  emoji: string;
  founded: number;
  languages: ("TR" | "EN")[];
  scholarships: boolean;
  note?: string;
}

export interface AbroadScholarship {
  id: string;
  name: string;
  country: string;
  flag: string;
  level: string;
  description: string;
  website: string;
  deadline?: string;
}

export interface YKSMajorEntry {
  major: string;
  yksType: YKSType;
  turkishEquivalent: string;
  note?: string;
}

export const TURKISH_UNIVERSITIES: TurkishUniversity[] = [
  {
    id: "odtu",
    name: "Orta Doğu Teknik Üniversitesi (ODTÜ)",
    nameEn: "Middle East Technical University (METU)",
    city: "Ankara",
    type: "state",
    yksTypes: ["SAY", "EA"],
    programs: ["Computer Engineering", "Architecture", "Civil Engineering", "Economics", "Aerospace Engineering"],
    qsRank: "269",
    tuition: "Free (state subsidy)",
    website: "https://www.metu.edu.tr",
    emoji: "🏛️",
    founded: 1956,
    languages: ["TR", "EN"],
    scholarships: true,
    note: "Instruction language: English. One of Turkey's most prestigious universities.",
  },
  {
    id: "bogazici",
    name: "Boğaziçi Üniversitesi",
    nameEn: "Boğaziçi University",
    city: "İstanbul",
    type: "state",
    yksTypes: ["SAY", "EA", "SÖZ"],
    programs: ["Electrical Engineering", "Management Information Systems", "International Trade", "Education", "Chemistry"],
    qsRank: "371",
    tuition: "Free (state subsidy)",
    website: "https://www.boun.edu.tr",
    emoji: "🌉",
    founded: 1863,
    languages: ["TR", "EN"],
    scholarships: true,
    note: "Instruction language: English. Founded as Robert College in 1863.",
  },
  {
    id: "itu",
    name: "İstanbul Teknik Üniversitesi (İTÜ)",
    nameEn: "Istanbul Technical University",
    city: "İstanbul",
    type: "state",
    yksTypes: ["SAY"],
    programs: ["Aerospace Engineering", "Naval Architecture", "Metallurgical Engineering", "Architecture", "Environmental Engineering"],
    qsRank: "298",
    tuition: "Free (state subsidy)",
    website: "https://www.itu.edu.tr",
    emoji: "⚙️",
    founded: 1773,
    languages: ["TR", "EN"],
    scholarships: true,
    note: "One of the world's oldest technical universities, founded in 1773.",
  },
  {
    id: "hacettepe",
    name: "Hacettepe Üniversitesi",
    nameEn: "Hacettepe University",
    city: "Ankara",
    type: "state",
    yksTypes: ["SAY", "EA", "SÖZ"],
    programs: ["Medicine", "Pharmacy", "Dentistry", "Nutrition & Dietetics", "Physiotherapy"],
    qsRank: "571",
    tuition: "Free (state subsidy)",
    website: "https://www.hacettepe.edu.tr",
    emoji: "⚕️",
    founded: 1967,
    languages: ["TR", "EN"],
    scholarships: true,
    note: "Turkey's leading university for health sciences and medicine.",
  },
  {
    id: "ankara",
    name: "Ankara Üniversitesi",
    nameEn: "Ankara University",
    city: "Ankara",
    type: "state",
    yksTypes: ["SAY", "EA", "SÖZ"],
    programs: ["Law", "Medicine", "Veterinary", "Political Science", "Pharmacy"],
    tuition: "Free (state subsidy)",
    website: "https://www.ankara.edu.tr",
    emoji: "⚖️",
    founded: 1946,
    languages: ["TR"],
    scholarships: true,
    note: "Turkey's first university after the founding of the Republic.",
  },
  {
    id: "istanbul",
    name: "İstanbul Üniversitesi",
    nameEn: "Istanbul University",
    city: "İstanbul",
    type: "state",
    yksTypes: ["SAY", "EA", "SÖZ"],
    programs: ["Medicine", "Law", "Business Administration", "Literature", "Sciences"],
    tuition: "Free (state subsidy)",
    website: "https://www.istanbul.edu.tr",
    emoji: "🕌",
    founded: 1453,
    languages: ["TR"],
    scholarships: true,
    note: "One of the world's oldest universities, with roots dating to 1453.",
  },
  {
    id: "ege",
    name: "Ege Üniversitesi",
    nameEn: "Ege University",
    city: "İzmir",
    type: "state",
    yksTypes: ["SAY", "EA", "SÖZ"],
    programs: ["Medicine", "Engineering", "Agriculture", "Sciences", "Communication"],
    tuition: "Free (state subsidy)",
    website: "https://www.ege.edu.tr",
    emoji: "🌊",
    founded: 1955,
    languages: ["TR", "EN"],
    scholarships: true,
  },
  {
    id: "deu",
    name: "Dokuz Eylül Üniversitesi",
    nameEn: "Dokuz Eylül University",
    city: "İzmir",
    type: "state",
    yksTypes: ["SAY", "EA", "SÖZ"],
    programs: ["Architecture", "Engineering", "Medicine", "Fine Arts", "Maritime Business"],
    tuition: "Free (state subsidy)",
    website: "https://www.deu.edu.tr",
    emoji: "🎭",
    founded: 1982,
    languages: ["TR", "EN"],
    scholarships: true,
  },
  {
    id: "gazi",
    name: "Gazi Üniversitesi",
    nameEn: "Gazi University",
    city: "Ankara",
    type: "state",
    yksTypes: ["SAY", "EA", "SÖZ"],
    programs: ["Education", "Engineering", "Medicine", "Dentistry", "Architecture"],
    tuition: "Free (state subsidy)",
    website: "https://www.gazi.edu.tr",
    emoji: "📚",
    founded: 1926,
    languages: ["TR"],
    scholarships: true,
    note: "Turkey's leading university for teacher education programs.",
  },
  {
    id: "bilkent",
    name: "Bilkent Üniversitesi",
    nameEn: "Bilkent University",
    city: "Ankara",
    type: "foundation",
    yksTypes: ["SAY", "EA", "SÖZ"],
    programs: ["Computer Science", "Electrical Engineering", "Business Administration", "Law", "Music & Performing Arts"],
    qsRank: "415",
    tuition: "₺180,000–350,000 / year",
    website: "https://www.bilkent.edu.tr",
    emoji: "🔬",
    founded: 1984,
    languages: ["TR", "EN"],
    scholarships: true,
    note: "Turkey's first private university. Full merit scholarships available. English instruction.",
  },
  {
    id: "koc",
    name: "Koç Üniversitesi",
    nameEn: "Koç University",
    city: "İstanbul",
    type: "foundation",
    yksTypes: ["SAY", "EA"],
    programs: ["Engineering", "Business Administration", "Medicine", "Law", "Sciences"],
    qsRank: "323",
    tuition: "₺200,000–400,000 / year",
    website: "https://www.ku.edu.tr",
    emoji: "🏆",
    founded: 1993,
    languages: ["TR", "EN"],
    scholarships: true,
    note: "Ranked among Turkey's top 3. Generous scholarship program. English instruction.",
  },
  {
    id: "sabanci",
    name: "Sabancı Üniversitesi",
    nameEn: "Sabancı University",
    city: "İstanbul",
    type: "foundation",
    yksTypes: ["SAY", "EA"],
    programs: ["Engineering & Natural Sciences", "Business", "Arts & Social Sciences", "Computer Science"],
    qsRank: "404",
    tuition: "₺180,000–360,000 / year",
    website: "https://www.sabanciuniv.edu.tr",
    emoji: "💡",
    founded: 1999,
    languages: ["TR", "EN"],
    scholarships: true,
    note: "Interdisciplinary approach — students choose their major after first year. English instruction.",
  },
  {
    id: "ozyegin",
    name: "Özyeğin Üniversitesi",
    nameEn: "Özyeğin University",
    city: "İstanbul",
    type: "foundation",
    yksTypes: ["SAY", "EA"],
    programs: ["Engineering", "Business Administration", "Architecture", "Law", "Psychology"],
    tuition: "₺150,000–300,000 / year",
    website: "https://www.ozyegin.edu.tr",
    emoji: "🌆",
    founded: 2007,
    languages: ["TR", "EN"],
    scholarships: true,
  },
  {
    id: "bau",
    name: "Bahçeşehir Üniversitesi (BAU)",
    nameEn: "Bahçeşehir University",
    city: "İstanbul",
    type: "foundation",
    yksTypes: ["SAY", "EA", "SÖZ"],
    programs: ["Engineering", "Architecture", "Law", "Communication", "Fine Arts & Design"],
    tuition: "₺130,000–280,000 / year",
    website: "https://www.bau.edu.tr",
    emoji: "🎨",
    founded: 1998,
    languages: ["TR", "EN"],
    scholarships: true,
  },
  {
    id: "tedu",
    name: "TED Üniversitesi",
    nameEn: "TED University",
    city: "Ankara",
    type: "foundation",
    yksTypes: ["SAY", "EA", "SÖZ"],
    programs: ["Engineering", "Business Administration", "Architecture", "Social Sciences", "Education"],
    tuition: "₺120,000–250,000 / year",
    website: "https://www.tedu.edu.tr",
    emoji: "🎓",
    founded: 2010,
    languages: ["TR", "EN"],
    scholarships: true,
    note: "Small campus community with a strong focus on teaching quality.",
  },
];

export const ABROAD_SCHOLARSHIPS: AbroadScholarship[] = [
  {
    id: "fulbright",
    name: "Fulbright Türkiye",
    country: "United States",
    flag: "🇺🇸",
    level: "Master's / PhD",
    description: "US government scholarship covering tuition, living expenses, and travel for graduate study in the USA. Highly competitive, awarded annually.",
    website: "https://www.fulbright.org.tr",
    deadline: "March (annually)",
  },
  {
    id: "daad",
    name: "DAAD Scholarships",
    country: "Germany",
    flag: "🇩🇪",
    level: "Bachelor's / Master's / PhD",
    description: "German Academic Exchange Service offers numerous grants for Turkish students to study or conduct research in Germany. Many programs available.",
    website: "https://www.daad.de/tr",
    deadline: "Varies by program",
  },
  {
    id: "chevening",
    name: "Chevening Scholarship",
    country: "United Kingdom",
    flag: "🇬🇧",
    level: "Master's",
    description: "UK government's global scholarship programme. Fully funded one-year Master's degree at any UK university for future leaders.",
    website: "https://www.chevening.org",
    deadline: "November (annually)",
  },
  {
    id: "erasmus",
    name: "Erasmus+",
    country: "Europe",
    flag: "🇪🇺",
    level: "Exchange (1 semester / 1 year)",
    description: "EU-funded exchange program allowing Turkish students at eligible universities to study abroad in Europe for one or two semesters with a monthly grant.",
    website: "https://www.erasmusplus.org.tr",
    deadline: "Varies by university",
  },
  {
    id: "tubitak",
    name: "TÜBİTAK 2214-A",
    country: "Worldwide",
    flag: "🌍",
    level: "PhD Research Support",
    description: "Turkish Scientific Council grant for PhD students to conduct 6–12 months of research at a foreign university. Covers travel, accommodation, and living costs.",
    website: "https://www.tubitak.gov.tr",
    deadline: "Varies by call",
  },
  {
    id: "holland",
    name: "Holland Scholarship",
    country: "Netherlands",
    flag: "🇳🇱",
    level: "Bachelor's / Master's",
    description: "€5,000 one-time scholarship for non-EEA students including Turkish citizens to study a full degree program at a Dutch university.",
    website: "https://www.studyinholland.nl",
    deadline: "April (annually)",
  },
  {
    id: "swiss",
    name: "Swiss Government Excellence",
    country: "Switzerland",
    flag: "🇨🇭",
    level: "Master's / PhD / Postdoc",
    description: "Fully funded scholarship for graduate and postdoctoral research at Swiss universities (ETH Zurich, EPFL, etc.). Covers tuition, housing, and stipend.",
    website: "https://www.sbfi.admin.ch/scholarships",
    deadline: "November (annually)",
  },
  {
    id: "turkiye_burslari",
    name: "Türkiye Bursları (Inbound)",
    country: "Turkey",
    flag: "🇹🇷",
    level: "Bachelor's / Master's / PhD",
    description: "For international students who want to study IN Turkey. Covers tuition, accommodation, monthly stipend, and health insurance at Turkish universities.",
    website: "https://www.turkiyeburslari.gov.tr",
    deadline: "February (annually)",
  },
];

export const YKS_MAJOR_MAP: YKSMajorEntry[] = [
  { major: "Computer Science & Software Engineering", yksType: "SAY", turkishEquivalent: "Bilgisayar Mühendisliği" },
  { major: "Business Administration & Management", yksType: "EA", turkishEquivalent: "İşletme / Yönetim" },
  { major: "Medicine & Health Sciences", yksType: "SAY", turkishEquivalent: "Tıp / Sağlık Bilimleri" },
  { major: "Creative Arts & Graphic Design", yksType: "SAY", turkishEquivalent: "Grafik Tasarım (+ Özel Yetenek)" },
  { major: "Environmental Science & Sustainability", yksType: "SAY", turkishEquivalent: "Çevre Mühendisliği" },
  { major: "Psychology & Social Sciences", yksType: "EA", turkishEquivalent: "Psikoloji / Sosyal Bilimler" },
  { major: "Law & Political Science", yksType: "EA", turkishEquivalent: "Hukuk / Siyaset Bilimi" },
  { major: "Mechanical & Civil Engineering", yksType: "SAY", turkishEquivalent: "Makine / İnşaat Mühendisliği" },
  { major: "Data Science & Statistics", yksType: "SAY", turkishEquivalent: "İstatistik / Veri Bilimi" },
  { major: "Education & Teaching", yksType: "SÖZ", turkishEquivalent: "Öğretmenlik / Eğitim Bilimleri" },
  { major: "Finance & Economics", yksType: "EA", turkishEquivalent: "Finans / İktisat" },
  { major: "Architecture & Urban Design", yksType: "SAY", turkishEquivalent: "Mimarlık / Şehir Planlama" },
  { major: "Pharmacy & Biomedical Sciences", yksType: "SAY", turkishEquivalent: "Eczacılık / Biyomedikal" },
  { major: "Communication & Media Studies", yksType: "EA", turkishEquivalent: "İletişim / Medya" },
  { major: "International Relations & Global Affairs", yksType: "EA", turkishEquivalent: "Uluslararası İlişkiler" },
  { major: "Cybersecurity & Network Engineering", yksType: "SAY", turkishEquivalent: "Siber Güvenlik / Ağ Mühendisliği" },
  { major: "Game Design & Interactive Media", yksType: "SAY", turkishEquivalent: "Oyun Tasarımı" },
  { major: "Nursing & Allied Health", yksType: "SAY", turkishEquivalent: "Hemşirelik / Sağlık Bilimleri" },
  { major: "Marketing & Advertising", yksType: "EA", turkishEquivalent: "Pazarlama / Reklamcılık" },
  { major: "Linguistics & Translation", yksType: "DİL", turkishEquivalent: "Mütercim-Tercümanlık / Dilbilim" },
];

export const YKS_TYPE_INFO: Record<YKSType, {
  label: string; labelTR: string; labelDE: string;
  color: string; bg: string; border: string; badge: string;
  description: string; descriptionTR: string; descriptionDE: string;
  icon: string;
}> = {
  SAY: {
    label: "SAY — Mathematics",
    labelTR: "SAY — Sayısal",
    labelDE: "SAY — Mathematik",
    icon: "📐",
    color: "text-blue-600 dark:text-blue-400",
    bg: "bg-blue-50 dark:bg-blue-950/30",
    border: "border-blue-200 dark:border-blue-800",
    badge: "bg-blue-100 dark:bg-blue-900/50 text-blue-700 dark:text-blue-300 border-blue-200 dark:border-blue-700",
    description: "Engineering, Medicine, Computer Science, Architecture, Sciences",
    descriptionTR: "Mühendislik, Tıp, Bilgisayar Bilimleri, Mimarlık, Fen Bilimleri",
    descriptionDE: "Ingenieurwesen, Medizin, Informatik, Architektur, Naturwissenschaften",
  },
  EA: {
    label: "EA — Equal Weight",
    labelTR: "EA — Eşit Ağırlık",
    labelDE: "EA — Gleichgewicht",
    icon: "⚖️",
    color: "text-purple-600 dark:text-purple-400",
    bg: "bg-purple-50 dark:bg-purple-950/30",
    border: "border-purple-200 dark:border-purple-800",
    badge: "bg-purple-100 dark:bg-purple-900/50 text-purple-700 dark:text-purple-300 border-purple-200 dark:border-purple-700",
    description: "Law, Business, Economics, Psychology, International Relations",
    descriptionTR: "Hukuk, İşletme, İktisat, Psikoloji, Uluslararası İlişkiler",
    descriptionDE: "Recht, Wirtschaft, Psychologie, Internationale Beziehungen",
  },
  "SÖZ": {
    label: "SÖZ — Verbal",
    labelTR: "SÖZ — Sözel",
    labelDE: "SÖZ — Verbal",
    icon: "📖",
    color: "text-amber-600 dark:text-amber-400",
    bg: "bg-amber-50 dark:bg-amber-950/30",
    border: "border-amber-200 dark:border-amber-800",
    badge: "bg-amber-100 dark:bg-amber-900/50 text-amber-700 dark:text-amber-300 border-amber-200 dark:border-amber-700",
    description: "Literature, History, Sociology, Education, Social Sciences",
    descriptionTR: "Edebiyat, Tarih, Sosyoloji, Eğitim, Sosyal Bilimler",
    descriptionDE: "Literatur, Geschichte, Soziologie, Bildung, Sozialwissenschaften",
  },
  "DİL": {
    label: "DİL — Language",
    labelTR: "DİL — Yabancı Dil",
    labelDE: "DİL — Sprache",
    icon: "🌐",
    color: "text-emerald-600 dark:text-emerald-400",
    bg: "bg-emerald-50 dark:bg-emerald-950/30",
    border: "border-emerald-200 dark:border-emerald-800",
    badge: "bg-emerald-100 dark:bg-emerald-900/50 text-emerald-700 dark:text-emerald-300 border-emerald-200 dark:border-emerald-700",
    description: "Translation, Linguistics, Foreign Language programs",
    descriptionTR: "Çeviri, Dilbilim, Yabancı Dil programları",
    descriptionDE: "Übersetzung, Linguistik, Fremdsprachenprogramme",
  },
};
