export interface UniversityInfo {
  country: string;
  city: string;
  website: string;
  founded: number;
  type: "Public" | "Private";
  description: string;
  tuitionEU?: string;
  tuitionNonEU?: string;
  tuitionDomestic?: string;
  tuitionIntl?: string;
  acceptanceRate?: string;
  totalStudents?: string;
  ielts?: string;
  toefl?: string;
  strengths: string[];
  notableFor?: string;
}

export const UNIVERSITY_DETAILS: Record<string, UniversityInfo> = {
  "MIT": {
    country: "United States", city: "Cambridge, MA", website: "https://mit.edu",
    founded: 1861, type: "Private",
    description: "MIT is the world's leading institution for science, technology, and engineering research. Known for its rigorous academics and entrepreneurial culture.",
    tuitionIntl: "$61,990/year", acceptanceRate: "4.5%", totalStudents: "11,500",
    ielts: "Not required (TOEFL preferred)", toefl: "90+",
    strengths: ["Engineering & Technology", "Entrepreneurship", "Research Output", "Industry Connections", "Innovation Culture"],
    notableFor: "Producing more Nobel laureates and startup founders than almost any institution.",
  },
  "University of Cambridge": {
    country: "United Kingdom", city: "Cambridge", website: "https://cam.ac.uk",
    founded: 1209, type: "Public",
    description: "One of the world's oldest and most prestigious universities, Cambridge offers a unique collegiate system with world-class research across all disciplines.",
    tuitionDomestic: "£9,535/year (UK students)", tuitionIntl: "£22,000–£58,000/year (EU & international)",
    acceptanceRate: "21%", totalStudents: "24,000", ielts: "7.5", toefl: "110",
    strengths: ["Natural Sciences", "Mathematics", "Law", "Medicine", "Economics"],
    notableFor: "Collegiate system allowing deep academic community and mentorship.",
  },
  "University of Oxford": {
    country: "United Kingdom", city: "Oxford", website: "https://ox.ac.uk",
    founded: 1096, type: "Public",
    description: "The oldest university in the English-speaking world, Oxford combines 900+ years of academic tradition with cutting-edge research across all fields.",
    tuitionDomestic: "£9,535/year (UK students)", tuitionIntl: "£26,000–£39,000/year (EU & international)",
    acceptanceRate: "17%", totalStudents: "26,000", ielts: "7.5", toefl: "110",
    strengths: ["Philosophy & Humanities", "Law", "Medicine", "Politics", "Economics"],
    notableFor: "Home to 30 UK Prime Ministers and 28 Nobel Prize winners.",
  },
  "Harvard University": {
    country: "United States", city: "Cambridge, MA", website: "https://harvard.edu",
    founded: 1636, type: "Private",
    description: "America's oldest university and a global leader in education, Harvard has an unmatched network, endowment, and breadth of academic excellence.",
    tuitionIntl: "$56,550/year", acceptanceRate: "3.6%", totalStudents: "23,000",
    ielts: "7.0", toefl: "100",
    strengths: ["Law", "Medicine", "Business", "Public Policy", "Research"],
    notableFor: "Largest university endowment in the world ($50+ billion).",
  },
  "Stanford University": {
    country: "United States", city: "Stanford, CA", website: "https://stanford.edu",
    founded: 1885, type: "Private",
    description: "Located in Silicon Valley, Stanford is synonymous with innovation and entrepreneurship, producing the founders of Google, HP, Netflix, and countless others.",
    tuitionIntl: "$65,127/year", acceptanceRate: "4%", totalStudents: "17,000",
    ielts: "Not required", toefl: "100",
    strengths: ["Computer Science", "Engineering", "Business", "Medicine", "Entrepreneurship"],
    notableFor: "Graduates have founded companies worth $2.7 trillion combined.",
  },
  "Imperial College London": {
    country: "United Kingdom", city: "London", website: "https://imperial.ac.uk",
    founded: 1907, type: "Public",
    description: "A world-class science, engineering, medicine and business university located in central London with exceptional industry partnerships.",
    tuitionDomestic: "£9,535/year (UK students)", tuitionIntl: "£30,000–£43,000/year (EU & international)",
    acceptanceRate: "14%", totalStudents: "19,000", ielts: "6.5", toefl: "92",
    strengths: ["Engineering", "Medicine", "Science", "Finance", "Business"],
    notableFor: "Located in South Kensington — the heart of London's knowledge quarter.",
  },
  "ETH Zurich": {
    country: "Switzerland", city: "Zurich", website: "https://ethz.ch",
    founded: 1855, type: "Public",
    description: "Switzerland's leading science and technology university, ETH Zurich is Europe's answer to MIT with exceptional research output and industry links.",
    tuitionEU: "CHF 730/semester (~€750)", tuitionNonEU: "CHF 2,190/semester (~€2,250) — since autumn 2025",
    acceptanceRate: "27%", totalStudents: "24,000", ielts: "7.0", toefl: "100",
    strengths: ["Engineering", "Computer Science", "Physics", "Mathematics", "Architecture"],
    notableFor: "Albert Einstein studied here. Tuition is extremely low for a top-10 university.",
  },
  "EPFL": {
    country: "Switzerland", city: "Lausanne", website: "https://epfl.ch",
    founded: 1969, type: "Public",
    description: "EPFL is one of Europe's most vibrant tech universities, known for robotics, digital humanities, and cutting-edge engineering research.",
    tuitionEU: "CHF 730/semester (~€750)", tuitionNonEU: "CHF 2,190/semester (~€2,250) — since autumn 2025",
    acceptanceRate: "33%", totalStudents: "11,000", ielts: "7.0", toefl: "100",
    strengths: ["Engineering", "Computer Science", "Life Sciences", "Robotics", "Digital Humanities"],
    notableFor: "One of the most international campuses in Europe — 60%+ international students.",
  },
  "TU Munich": {
    country: "Germany", city: "Munich", website: "https://tum.de",
    founded: 1868, type: "Public",
    description: "Germany's top technical university and one of Europe's leading research institutions, TUM excels in engineering, natural sciences, and medicine.",
    tuitionEU: "~€144/semester (admin fee only)", tuitionNonEU: "€2,000–€3,000/semester (undergrad) / €4,000–€6,000 (master's) — since 2024",
    acceptanceRate: "8%", totalStudents: "50,000", ielts: "6.5", toefl: "88",
    strengths: ["Engineering", "Computer Science", "Medicine", "Natural Sciences", "Business"],
    notableFor: "One of Germany's Elite Universities — strong industry partnerships with BMW, Siemens, and MAN.",
  },
  "University of Melbourne": {
    country: "Australia", city: "Melbourne", website: "https://unimelb.edu.au",
    founded: 1853, type: "Public",
    description: "Australia's leading research university, Melbourne is consistently ranked among the world's top 15 universities with excellent graduate outcomes.",
    tuitionDomestic: "AU$10,000/year", tuitionIntl: "AU$35,000–$50,000/year",
    acceptanceRate: "70%", totalStudents: "52,000", ielts: "6.5", toefl: "79",
    strengths: ["Medicine", "Law", "Engineering", "Arts", "Business"],
    notableFor: "Uses a unique Melbourne Model — broad undergraduate degree followed by specialised graduate school.",
  },
  "University of Toronto": {
    country: "Canada", city: "Toronto", website: "https://utoronto.ca",
    founded: 1827, type: "Public",
    description: "Canada's top-ranked university and one of North America's great research institutions, offering unparalleled diversity in one of the world's most livable cities.",
    tuitionDomestic: "CA$6,500/year", tuitionIntl: "CA$45,000–$65,000/year",
    acceptanceRate: "43%", totalStudents: "97,000", ielts: "6.5", toefl: "89",
    strengths: ["Medicine", "Computer Science", "Engineering", "Business", "Social Sciences"],
    notableFor: "Largest university in Canada with one of the most diverse student bodies in the world.",
  },
  "McGill University": {
    country: "Canada", city: "Montreal", website: "https://mcgill.ca",
    founded: 1821, type: "Public",
    description: "Canada's most international university, McGill is located in vibrant Montreal and offers world-class education with a distinctly cosmopolitan feel.",
    tuitionDomestic: "CA$4,000/year", tuitionIntl: "CA$20,000–$30,000/year",
    acceptanceRate: "46%", totalStudents: "40,000", ielts: "6.5", toefl: "86",
    strengths: ["Medicine", "Law", "Engineering", "Music", "Social Sciences"],
    notableFor: "English-language education in French-speaking Montreal — bilingual advantage.",
  },
  "UCL": {
    country: "United Kingdom", city: "London", website: "https://ucl.ac.uk",
    founded: 1826, type: "Public",
    description: "London's global university, UCL is at the forefront of research and innovation with a diverse international community and unbeatable London location.",
    tuitionDomestic: "£9,535/year (UK students)", tuitionIntl: "£20,000–£35,000/year (EU & international)",
    acceptanceRate: "63%", totalStudents: "42,000", ielts: "7.0", toefl: "100",
    strengths: ["Architecture", "Medicine", "Law", "Engineering", "Social Sciences"],
    notableFor: "Founded on the principles of being open to all regardless of religion or class.",
  },
  "NUS": {
    country: "Singapore", city: "Singapore", website: "https://nus.edu.sg",
    founded: 1905, type: "Public",
    description: "Asia's leading global university, NUS offers world-class education in a vibrant Asian hub connecting East and West.",
    tuitionDomestic: "S$8,800/year", tuitionIntl: "S$17,000–$26,000/year",
    acceptanceRate: "5%", totalStudents: "40,000", ielts: "6.0", toefl: "85",
    strengths: ["Engineering", "Business", "Law", "Medicine", "Computing"],
    notableFor: "Gateway to Asia's booming economy — graduates work across ASEAN, China, and beyond.",
  },
  "University of Edinburgh": {
    country: "United Kingdom", city: "Edinburgh", website: "https://ed.ac.uk",
    founded: 1583, type: "Public",
    description: "One of the world's great universities, Edinburgh combines historic prestige with modern research excellence in Scotland's vibrant capital city.",
    tuitionDomestic: "Free (Scottish students) / £9,535 (rest of UK)", tuitionIntl: "£18,000–£33,000/year (EU & international)",
    acceptanceRate: "44%", totalStudents: "44,000", ielts: "6.5", toefl: "92",
    strengths: ["Medicine", "Informatics", "Law", "Arts", "Business"],
    notableFor: "Home of the Enlightenment — birthplace of modern philosophy and economics.",
  },
  "University of British Columbia": {
    country: "Canada", city: "Vancouver", website: "https://ubc.ca",
    founded: 1908, type: "Public",
    description: "Located on Canada's stunning Pacific coast, UBC is a world-class research university known for sustainability, innovation, and exceptional quality of life.",
    tuitionDomestic: "CA$5,000/year", tuitionIntl: "CA$35,000–$48,000/year",
    acceptanceRate: "52%", totalStudents: "66,000", ielts: "6.5", toefl: "90",
    strengths: ["Forestry", "Medicine", "Engineering", "Business", "Environmental Science"],
    notableFor: "One of the most beautiful university campuses in the world — ocean and mountain views.",
  },
  "TU Delft": {
    country: "Netherlands", city: "Delft", website: "https://tudelft.nl",
    founded: 1842, type: "Public",
    description: "The Netherlands' largest and most comprehensive technical university, TU Delft is consistently ranked among Europe's top engineering schools.",
    tuitionEU: "€2,530/year", tuitionNonEU: "€16,000–€20,000/year",
    acceptanceRate: "32%", totalStudents: "27,000", ielts: "6.5", toefl: "90",
    strengths: ["Architecture", "Aerospace", "Civil Engineering", "Industrial Design", "Computer Science"],
    notableFor: "One of the oldest polytechnic universities in the world.",
  },
  "Karolinska Institute": {
    country: "Sweden", city: "Stockholm", website: "https://ki.se",
    founded: 1810, type: "Public",
    description: "One of the world's foremost medical universities, Karolinska Institute awards the Nobel Prize in Physiology or Medicine and leads global health research.",
    tuitionEU: "Free (EU/EEA students)", tuitionNonEU: "SEK 100,000–195,000/year (~€9,000–€18,000)",
    acceptanceRate: "9%", totalStudents: "7,000", ielts: "6.5", toefl: "90",
    strengths: ["Medicine", "Nursing", "Biomedical Sciences", "Public Health", "Neuroscience"],
    notableFor: "Decides who wins the Nobel Prize in Medicine every year.",
  },
  "LMU Munich": {
    country: "Germany", city: "Munich", website: "https://lmu.de",
    founded: 1472, type: "Public",
    description: "One of Germany's oldest and most prestigious universities, LMU combines a rich 500-year history with modern excellence in research and teaching.",
    tuitionEU: "~€144/semester (admin fee only)", tuitionNonEU: "€2,000–€3,000/semester (non-EU) — since 2024",
    acceptanceRate: "15%", totalStudents: "52,000", ielts: "6.5", toefl: "88",
    strengths: ["Medicine", "Law", "Natural Sciences", "Philosophy", "Statistics"],
    notableFor: "37 Nobel laureates associated — more than most countries in the world.",
  },
  "University of Amsterdam": {
    country: "Netherlands", city: "Amsterdam", website: "https://uva.nl",
    founded: 1632, type: "Public",
    description: "Located in one of Europe's most vibrant cities, UvA is the Netherlands' largest research university with a rich academic tradition and cosmopolitan atmosphere.",
    tuitionEU: "€2,530/year", tuitionNonEU: "€12,000–€16,000/year",
    acceptanceRate: "40%", totalStudents: "44,000", ielts: "6.5", toefl: "92",
    strengths: ["Law", "Social Sciences", "Psychology", "Economics", "Arts"],
    notableFor: "Most programs offered in English — truly international student community.",
  },
  "RWTH Aachen": {
    country: "Germany", city: "Aachen", website: "https://rwth-aachen.de",
    founded: 1870, type: "Public",
    description: "Germany's largest technical university and one of Europe's top engineering schools, RWTH Aachen has strong ties with major German and European industry.",
    tuitionEU: "€300/semester (admin fee)", tuitionNonEU: "€300/semester (admin fee)",
    acceptanceRate: "18%", totalStudents: "45,000", ielts: "6.5", toefl: "88",
    strengths: ["Mechanical Engineering", "Electrical Engineering", "Computer Science", "Chemistry", "Architecture"],
    notableFor: "Deep partnerships with BMW, Ford, and major German manufacturers.",
  },
  "University of Waterloo": {
    country: "Canada", city: "Waterloo, Ontario", website: "https://uwaterloo.ca",
    founded: 1957, type: "Public",
    description: "Canada's top university for math, computer science, and engineering, Waterloo's co-op program gives students unrivaled industry experience.",
    tuitionDomestic: "CA$6,000/year", tuitionIntl: "CA$35,000–$55,000/year",
    acceptanceRate: "53%", totalStudents: "42,000", ielts: "6.5", toefl: "88",
    strengths: ["Computer Science", "Mathematics", "Engineering", "Co-op Education", "Quantum Computing"],
    notableFor: "World's largest co-op education program — graduates hired by Google, Meta, Microsoft.",
  },
  "London School of Economics": {
    country: "United Kingdom", city: "London", website: "https://lse.ac.uk",
    founded: 1895, type: "Public",
    description: "The world's leading social sciences university, LSE is at the centre of global economics, politics, and law with an unmatched professional network.",
    tuitionDomestic: "£9,535/year (UK students)", tuitionIntl: "£20,000–£25,000/year (EU & international)",
    acceptanceRate: "16%", totalStudents: "12,000", ielts: "7.0", toefl: "107",
    strengths: ["Economics", "Law", "Political Science", "International Relations", "Finance"],
    notableFor: "Alumni run the World Bank, IMF, and central banks across the globe.",
  },
  "HEC Paris": {
    country: "France", city: "Jouy-en-Josas", website: "https://hec.edu",
    founded: 1881, type: "Private",
    description: "Europe's top-ranked business school, HEC Paris develops global business leaders through rigorous academics and an elite international network.",
    tuitionIntl: "€37,000–€68,000/year (MBA)",
    acceptanceRate: "12%", totalStudents: "4,500", ielts: "7.0", toefl: "100",
    strengths: ["MBA", "Finance", "Strategy", "Entrepreneurship", "Luxury Management"],
    notableFor: "Consistently ranked #1 in Europe for MBA programs.",
  },
  "Wageningen University": {
    country: "Netherlands", city: "Wageningen", website: "https://wur.nl",
    founded: 1918, type: "Public",
    description: "The world's leading university for life sciences and sustainability, Wageningen specializes in food, agriculture, and environmental research.",
    tuitionEU: "€2,530/year", tuitionNonEU: "€12,000–€15,000/year",
    acceptanceRate: "40%", totalStudents: "14,000", ielts: "6.5", toefl: "90",
    strengths: ["Agriculture", "Food Science", "Environmental Studies", "Biology", "Sustainability"],
    notableFor: "Ranked #1 worldwide for agriculture and forestry.",
  },
  "Heidelberg University": {
    country: "Germany", city: "Heidelberg", website: "https://uni-heidelberg.de",
    founded: 1386, type: "Public",
    description: "Germany's oldest university, Heidelberg is famous for its beautiful old town setting and world-class research in natural sciences and medicine.",
    tuitionEU: "~€170/semester (admin fee only)", tuitionNonEU: "€1,500/semester + €170 admin (~€3,340/year) — Baden-Württemberg fee",
    acceptanceRate: "20%", totalStudents: "29,000", ielts: "6.5", toefl: "88",
    strengths: ["Medicine", "Natural Sciences", "Law", "Philosophy", "Economics"],
    notableFor: "Founded in 1386 — the oldest university in the German-speaking world.",
  },
  "KTH Royal Institute of Technology": {
    country: "Sweden", city: "Stockholm", website: "https://kth.se",
    founded: 1827, type: "Public",
    description: "Sweden's largest and most respected technical university, KTH is a key driver of Sweden's innovation economy with strong links to industry.",
    tuitionEU: "Free (EU/EEA students)", tuitionNonEU: "SEK 130,000–210,000/year (~€12,000–€20,000)",
    acceptanceRate: "25%", totalStudents: "18,000", ielts: "6.5", toefl: "90",
    strengths: ["Engineering", "Computer Science", "Architecture", "Industrial Management", "Sustainable Development"],
    notableFor: "Ericsson, Spotify, and King (Candy Crush) were all founded by KTH alumni.",
  },
  "University of Sydney": {
    country: "Australia", city: "Sydney", website: "https://sydney.edu.au",
    founded: 1850, type: "Public",
    description: "Australia's first university, the University of Sydney combines historic prestige with modern excellence, set in one of the world's most beautiful cities.",
    tuitionDomestic: "AU$10,000/year", tuitionIntl: "AU$35,000–$48,000/year",
    acceptanceRate: "30%", totalStudents: "73,000", ielts: "6.5", toefl: "85",
    strengths: ["Law", "Medicine", "Arts", "Engineering", "Business"],
    notableFor: "Iconic sandstone buildings in the heart of Sydney — one of Australia's most beautiful campuses.",
  },
  "ANU": {
    country: "Australia", city: "Canberra", website: "https://anu.edu.au",
    founded: 1946, type: "Public",
    description: "Australia's national university and the country's top-ranked institution by graduate outcomes, ANU is a research powerhouse in the national capital.",
    tuitionDomestic: "AU$9,000/year", tuitionIntl: "AU$35,000–$48,000/year",
    acceptanceRate: "35%", totalStudents: "25,000", ielts: "6.5", toefl: "80",
    strengths: ["Political Science", "International Relations", "Science", "Law", "Arts"],
    notableFor: "Directly advises the Australian government — best connected university in Canberra.",
  },
  "University of Manchester": {
    country: "United Kingdom", city: "Manchester", website: "https://manchester.ac.uk",
    founded: 1824, type: "Public",
    description: "A leading global research university in the heart of one of the UK's most vibrant cities, Manchester has a rich tradition of scientific discovery.",
    tuitionDomestic: "£9,535/year (UK students)", tuitionIntl: "£21,000–£34,000/year (EU & international)",
    acceptanceRate: "57%", totalStudents: "44,000", ielts: "6.5", toefl: "90",
    strengths: ["Engineering", "Medicine", "Business", "Arts", "Computer Science"],
    notableFor: "25 Nobel Prize winners among staff and alumni — including Ernest Rutherford who split the atom.",
  },
  "UNSW Sydney": {
    country: "Australia", city: "Sydney", website: "https://unsw.edu.au",
    founded: 1949, type: "Public",
    description: "Australia's global university for engineering, technology and business, UNSW is known for its strong industry connections and entrepreneurial culture.",
    tuitionDomestic: "AU$10,000/year", tuitionIntl: "AU$36,000–$52,000/year",
    acceptanceRate: "40%", totalStudents: "65,000", ielts: "6.5", toefl: "85",
    strengths: ["Engineering", "Law", "Business", "Medicine", "Arts & Social Sciences"],
    notableFor: "Produces the highest number of CEOs among Australian universities.",
  },
  "NTU": {
    country: "Singapore", city: "Singapore", website: "https://ntu.edu.sg",
    founded: 1981, type: "Public",
    description: "A young and rapidly rising global university, NTU Singapore is one of Asia's leading research institutions with state-of-the-art facilities.",
    tuitionDomestic: "S$8,800/year", tuitionIntl: "S$17,000–$26,000/year",
    acceptanceRate: "7%", totalStudents: "33,000", ielts: "6.0", toefl: "85",
    strengths: ["Engineering", "Business", "Science", "Humanities", "Data Science"],
    notableFor: "Ranked the world's best young university multiple times by QS.",
  },
  "Carnegie Mellon University": {
    country: "United States", city: "Pittsburgh, PA", website: "https://cmu.edu",
    founded: 1900, type: "Private",
    description: "CMU is the global leader in computer science, artificial intelligence, and robotics research, with exceptional programs in drama and business too.",
    tuitionIntl: "$62,260/year", acceptanceRate: "11%", totalStudents: "15,000",
    ielts: "7.0", toefl: "102",
    strengths: ["Computer Science", "AI/ML", "Robotics", "Drama", "Business"],
    notableFor: "The #1 computer science program in the world — where AI was born.",
  },
  "UC Berkeley": {
    country: "United States", city: "Berkeley, CA", website: "https://berkeley.edu",
    founded: 1868, type: "Public",
    description: "The world's premier public university, UC Berkeley combines world-class academics with a legendary tradition of free speech and social impact.",
    tuitionIntl: "$44,000/year", acceptanceRate: "14%", totalStudents: "45,000",
    ielts: "7.0", toefl: "80",
    strengths: ["Computer Science", "Engineering", "Law", "Environmental Science", "Business"],
    notableFor: "The most cited public university in the world — 107 Nobel laureates.",
  },
  "King's College London": {
    country: "United Kingdom", city: "London", website: "https://kcl.ac.uk",
    founded: 1829, type: "Public",
    description: "One of the UK's leading research universities in the heart of London with world-class health sciences and law programs.",
    tuitionDomestic: "£9,535/year (UK students)", tuitionIntl: "£19,000–£30,000/year (EU & international)",
    acceptanceRate: "25%", totalStudents: "33,000", ielts: "7.0", toefl: "100",
    strengths: ["Medicine", "Law", "Dentistry", "Nursing", "Social Sciences"],
    notableFor: "Located on the Thames in central London — five campuses across the city.",
  },
  "Monash University": {
    country: "Australia", city: "Melbourne", website: "https://monash.edu",
    founded: 1958, type: "Public",
    description: "Australia's largest university and one of its most international, Monash is known for strong professional programs and global connections.",
    tuitionDomestic: "AU$9,500/year", tuitionIntl: "AU$33,000–$46,000/year",
    acceptanceRate: "70%", totalStudents: "86,000", ielts: "6.5", toefl: "79",
    strengths: ["Medicine", "Engineering", "Business", "Law", "Pharmacy"],
    notableFor: "One of only three Australian universities with a medical school and law school.",
  },
  "University of Queensland": {
    country: "Australia", city: "Brisbane", website: "https://uq.edu.au",
    founded: 1909, type: "Public",
    description: "Queensland's flagship university with strong research in medicine, environmental science, and engineering.",
    tuitionDomestic: "AU$9,000/year", tuitionIntl: "AU$34,000–$48,000/year",
    acceptanceRate: "68%", totalStudents: "55,000", ielts: "6.5", toefl: "87",
    strengths: ["Medicine", "Engineering", "Business", "Environmental Science", "Law"],
    notableFor: "Home to Australia's largest solar research institute.",
  },
  "Lund University": {
    country: "Sweden", city: "Lund", website: "https://lu.se",
    founded: 1666, type: "Public",
    description: "One of Scandinavia's oldest and most prestigious universities with a strong international focus and vibrant student city.",
    tuitionEU: "Free (EU/EEA students)", tuitionNonEU: "SEK 90,000–135,000/year (~€8,000–€13,000)",
    totalStudents: "45,000", ielts: "6.5", toefl: "90",
    strengths: ["Engineering", "Medicine", "Social Sciences", "Law", "Technology"],
    notableFor: "Sweden's most popular university — one in seven Swedish students study here.",
  },
  "Uppsala University": {
    country: "Sweden", city: "Uppsala", website: "https://uu.se",
    founded: 1477, type: "Public",
    description: "Scandinavia's oldest university, Uppsala has a rich academic tradition and excellent research across all disciplines.",
    tuitionEU: "Free (EU/EEA students)", tuitionNonEU: "SEK 90,000–145,000/year",
    totalStudents: "48,000", ielts: "6.5", toefl: "90",
    strengths: ["Medicine", "Natural Sciences", "Social Sciences", "Pharmacy", "Law"],
    notableFor: "Founded in 1477 — the oldest university in the Nordic countries.",
  },
  "Utrecht University": {
    country: "Netherlands", city: "Utrecht", website: "https://uu.nl",
    founded: 1636, type: "Public",
    description: "One of Europe's leading research universities with strong programs in social sciences and life sciences in a beautiful Dutch city.",
    tuitionEU: "€2,530/year", tuitionNonEU: "€9,000–€16,000/year",
    totalStudents: "36,000", ielts: "6.5", toefl: "90",
    strengths: ["Social Sciences", "Natural Sciences", "Law", "Humanities", "Medicine"],
    notableFor: "Consistently ranked the best university in the Netherlands.",
  },
  "Leiden University": {
    country: "Netherlands", city: "Leiden", website: "https://universiteitleiden.nl",
    founded: 1575, type: "Public",
    description: "The Netherlands' oldest university with a distinguished history in law, humanities, and social sciences.",
    tuitionEU: "€2,530/year", tuitionNonEU: "€9,000–€16,000/year",
    totalStudents: "33,000", ielts: "6.5", toefl: "90",
    strengths: ["Law", "International Relations", "Social Sciences", "Humanities", "Science"],
    notableFor: "Alma mater of 16 Dutch prime ministers and René Descartes.",
  },
};

export function getUniversityInfo(name: string): UniversityInfo | null {
  if (UNIVERSITY_DETAILS[name]) return UNIVERSITY_DETAILS[name];
  // Try matching by prefix (e.g. "TU Munich (Klinikum)" → "TU Munich")
  const base = name.split(" (")[0].trim();
  if (UNIVERSITY_DETAILS[base]) return UNIVERSITY_DETAILS[base];
  // Try partial key match
  const key = Object.keys(UNIVERSITY_DETAILS).find(k =>
    name.toLowerCase().startsWith(k.toLowerCase()) ||
    k.toLowerCase().startsWith(base.toLowerCase())
  );
  return key ? UNIVERSITY_DETAILS[key] : null;
}
