export const UNIVERSITIES_BY_COUNTRY: Record<string, Record<string, string[]>> = {
  "Computer Science & Software Engineering": {
    "United States": ["MIT", "Stanford University", "Carnegie Mellon University", "UC Berkeley", "University of Washington"],
    "Germany": ["TU Munich (TUM)", "RWTH Aachen University", "KIT Karlsruhe", "TU Berlin", "University of Stuttgart"],
    "United Kingdom": ["Imperial College London", "University of Cambridge", "University of Edinburgh", "UCL", "University of Manchester"],
    "Canada": ["University of Toronto", "University of Waterloo", "University of British Columbia", "McGill University", "University of Alberta"],
    "Netherlands": ["TU Delft", "University of Amsterdam", "Eindhoven University of Technology", "Vrije Universiteit Amsterdam", "University of Twente"],
    "Sweden": ["KTH Royal Institute of Technology", "Chalmers University of Technology", "Uppsala University", "Lund University", "Linköping University"],
    "Switzerland": ["ETH Zurich", "EPFL", "University of Zurich", "University of Basel", "University of Bern"],
    "Australia": ["University of Melbourne", "University of Sydney", "UNSW Sydney", "ANU", "Monash University"],
  },
  "Medicine & Health Sciences": {
    "United Kingdom": ["University of Oxford", "University of Cambridge", "Imperial College London", "King's College London", "University of Edinburgh"],
    "United States": ["Harvard Medical School", "Johns Hopkins University", "Stanford Medicine", "Mayo Clinic Alix School", "UCSF"],
    "Germany": ["Heidelberg University", "LMU Munich", "Charité — Universitätsmedizin Berlin", "TU Munich (Klinikum)", "University of Göttingen"],
    "Netherlands": ["Amsterdam UMC", "Erasmus MC", "Leiden University Medical Centre", "Maastricht University", "Radboud University"],
    "Australia": ["University of Melbourne", "University of Sydney", "Monash University", "University of Queensland", "ANU Medical School"],
    "Sweden": ["Karolinska Institute", "Uppsala University", "University of Gothenburg", "Lund University", "Umeå University"],
    "France": ["Paris Cité University (Paris Descartes)", "Sorbonne University", "University of Strasbourg", "Aix-Marseille University", "University of Bordeaux"],
  },
  "Business Administration & Management": {
    "United States": ["Wharton School (UPenn)", "Harvard Business School", "MIT Sloan", "Columbia Business School", "Booth School (UChicago)"],
    "United Kingdom": ["London Business School", "Oxford Saïd Business School", "Cambridge Judge Business School", "Imperial College Business School", "Warwick Business School"],
    "France": ["HEC Paris", "INSEAD (Fontainebleau)", "ESSEC Business School", "Sciences Po (Paris)", "EM Lyon Business School"],
    "Germany": ["WHU – Otto Beisheim School", "Mannheim Business School", "Frankfurt School of Finance", "HHL Leipzig Graduate School", "ESMT Berlin"],
    "Netherlands": ["Rotterdam School of Management (Erasmus)", "Amsterdam Business School", "Tilburg University", "University of Groningen", "Maastricht University SBE"],
    "Switzerland": ["IMD Business School (Lausanne)", "University of St. Gallen (HSG)", "Geneva School of Economics", "HEC Lausanne (UNIL)", "ZHAW School of Management"],
    "Singapore": ["NUS Business School", "NTU Nanyang Business School", "INSEAD Asia Campus", "SMU Lee Kong Chian School", "Singapore Management University"],
    "Canada": ["Ivey Business School (Western)", "Rotman School of Management (UofT)", "McGill Desautels Faculty", "Schulich School (York)", "HEC Montréal"],
  },
  "Law & Political Science": {
    "United Kingdom": ["University of Oxford (Law)", "University of Cambridge (Law)", "London School of Economics", "King's College London", "UCL Faculty of Laws"],
    "United States": ["Yale Law School", "Harvard Law School", "Columbia Law School", "NYU School of Law", "University of Chicago Law"],
    "Germany": ["Humboldt University Berlin", "LMU Munich (Law)", "University of Heidelberg", "University of Hamburg (Law)", "Freie Universität Berlin"],
    "Netherlands": ["Utrecht University (Law)", "Leiden University (Law)", "Maastricht University (Law)", "University of Amsterdam (Law)", "Tilburg Law School"],
    "Australia": ["University of Melbourne (Law)", "University of Sydney Law School", "ANU College of Law", "Monash Law School", "University of Queensland Law"],
    "France": ["Paris I Panthéon-Sorbonne", "Sciences Po Paris (Law)", "Université Paris II Assas", "University of Strasbourg (Law)", "University of Bordeaux (Law)"],
    "Canada": ["Osgoode Hall Law School (York)", "McGill Faculty of Law", "University of Toronto Law", "University of British Columbia Law", "Dalhousie Law School"],
  },
  "Mechanical & Civil Engineering": {
    "United States": ["MIT (Engineering)", "Stanford University", "Caltech", "Georgia Tech", "University of Michigan"],
    "Germany": ["TU Munich", "RWTH Aachen", "TU Berlin", "KIT Karlsruhe", "University of Stuttgart"],
    "United Kingdom": ["Imperial College London", "University of Cambridge", "University of Southampton", "University of Bristol", "University of Manchester"],
    "Netherlands": ["TU Delft", "Eindhoven University of Technology", "University of Twente", "Vrije Universiteit Amsterdam", "Wageningen University"],
    "Sweden": ["Chalmers University of Technology", "KTH Royal Institute of Technology", "Lund University", "Linköping University", "Uppsala University"],
    "Australia": ["University of Melbourne", "University of New South Wales", "Monash University", "University of Queensland", "University of Adelaide"],
    "Canada": ["University of Toronto", "University of Waterloo", "University of British Columbia", "McGill University", "University of Alberta"],
    "Switzerland": ["ETH Zurich", "EPFL", "University of Applied Sciences Lucerne", "ZHAW", "University of Bern"],
  },
  "Psychology & Social Sciences": {
    "United Kingdom": ["University of Cambridge", "University College London", "University of Edinburgh", "University of Exeter", "University of Bristol"],
    "United States": ["Harvard University (Psychology)", "Stanford University", "Yale University", "University of Michigan", "UC San Diego"],
    "Netherlands": ["University of Amsterdam", "Utrecht University", "Leiden University", "Tilburg University", "Radboud University Nijmegen"],
    "Germany": ["Heidelberg University", "LMU Munich", "Freie Universität Berlin", "Humboldt University Berlin", "University of Tübingen"],
    "Australia": ["University of Melbourne", "Australian National University", "University of Queensland", "University of Sydney", "Monash University"],
    "Sweden": ["Stockholm University", "Uppsala University", "Lund University", "Göteborg University", "Umeå University"],
    "Canada": ["University of Toronto", "McGill University", "University of British Columbia", "University of Waterloo", "University of Alberta"],
  },
  "Creative Arts & Graphic Design": {
    "United Kingdom": ["Royal College of Art (London)", "Goldsmiths (University of London)", "Central Saint Martins (UAL)", "University of the Arts London", "Falmouth University"],
    "United States": ["Rhode Island School of Design (RISD)", "Pratt Institute", "Parsons School of Design (The New School)", "ArtCenter College of Design", "SCAD (Savannah)"],
    "Netherlands": ["Design Academy Eindhoven", "Gerrit Rietveld Academie (Amsterdam)", "ArtEZ University of the Arts", "Royal Academy of Art The Hague", "HKU University of the Arts Utrecht"],
    "Germany": ["Bauhaus-Universität Weimar", "HfG Offenbach", "Berlin University of the Arts", "KISD Cologne", "Academy of Fine Arts Munich"],
    "Italy": ["Politecnico di Milano (Design)", "Istituto Marangoni (Milan)", "Accademia di Belle Arti Firenze", "NABA (Milan)", "ISIA Roma Design"],
    "Australia": ["RMIT University (Design)", "University of Technology Sydney", "Griffith College of Art", "University of Melbourne (Fine Arts)", "Queensland College of Art"],
    "Spain": ["IED Madrid (Istituto Europeo di Design)", "ELISAVA Barcelona", "Escola Massana (Barcelona)", "ESDESIGN Barcelona", "ESDIP Madrid"],
  },
  "Environmental Science & Sustainability": {
    "United Kingdom": ["University of Cambridge (Environmental)", "Imperial College London", "University of Edinburgh", "University of Leeds", "University of Southampton"],
    "United States": ["Yale School of the Environment", "UC Berkeley (Environmental Sciences)", "University of Michigan (SNRE)", "Duke Nicholas School", "Colorado State University"],
    "Germany": ["Leuphana University Lüneburg", "University of Freiburg (Environmental)", "TU Berlin (Environmental Planning)", "KIT (Environmental Engineering)", "University of Greifswald"],
    "Netherlands": ["Wageningen University (WUR)", "Utrecht University (Geosciences)", "Leiden University (CML)", "VU Amsterdam", "University of Groningen"],
    "Sweden": ["Stockholm University (Stockholm Resilience Centre)", "Lund University (LUCSUS)", "Uppsala University", "Linköping University", "Umeå University"],
    "Australia": ["Australian National University", "University of Melbourne", "UNSW Sydney (Environmental)", "James Cook University (Marine)", "Murdoch University"],
    "Canada": ["McGill University (Environment)", "UBC (Institute for Resources, Environment)", "Dalhousie University", "University of Waterloo", "University of Victoria"],
  },
  "Data Science & Statistics": {
    "United States": ["MIT (EECS / Statistics)", "Stanford (Statistics)", "Carnegie Mellon (Machine Learning)", "UC Berkeley (CDSS)", "University of Chicago (Statistics)"],
    "United Kingdom": ["University of Oxford (Statistics)", "University of Cambridge (MPhil Statistics)", "Imperial College London", "UCL (CS / Stats)", "University of Edinburgh"],
    "Germany": ["LMU Munich (Statistics / Data Science)", "TU Munich", "Humboldt University Berlin", "University of Mannheim", "RWTH Aachen"],
    "Netherlands": ["Eindhoven University of Technology", "TU Delft", "University of Amsterdam", "Utrecht University", "Vrije Universiteit Amsterdam"],
    "Switzerland": ["ETH Zurich (Data Science)", "EPFL (Computer and Communication Sciences)", "University of Zurich", "University of Lausanne", "University of Bern"],
    "Canada": ["University of Toronto", "University of Waterloo (Statistics)", "McGill University", "Simon Fraser University", "University of British Columbia"],
    "Australia": ["University of Melbourne", "ANU (Statistics)", "University of Sydney", "Monash University (Data Science)", "University of Queensland"],
    "Singapore": ["NUS (Statistics & Data Science)", "NTU (Data Science)", "Singapore Management University (IS)", "Singapore Institute of Technology", "SUTD"],
  },
  "Education & Teaching": {
    "United Kingdom": ["UCL Institute of Education", "University of Cambridge (Faculty of Education)", "University of Oxford (Dept of Education)", "University of Edinburgh", "University of Bristol"],
    "United States": ["Harvard Graduate School of Education", "Stanford Graduate School of Education", "Teachers College Columbia", "University of Michigan (Education)", "Vanderbilt Peabody College"],
    "Netherlands": ["Leiden University (Education Science)", "University of Amsterdam (Education)", "Utrecht University", "Radboud University Nijmegen", "VU Amsterdam"],
    "Germany": ["University of Munich (Teacher Training)", "Humboldt University Berlin (Education)", "University of Hamburg", "University of Cologne (Education)", "University of Frankfurt"],
    "Finland": ["University of Helsinki (Faculty of Educational Sciences)", "University of Tampere", "University of Jyväskylä", "University of Turku", "Åbo Akademi University"],
    "Australia": ["University of Melbourne (Graduate School of Education)", "Monash University (Education)", "University of Sydney", "Queensland University of Technology", "Australian Catholic University"],
    "Canada": ["OISE — University of Toronto", "University of British Columbia (Faculty of Education)", "McGill Faculty of Education", "York Faculty of Education", "University of Alberta (Education)"],
  },
  "Finance & Economics": {
    "United States": ["Wharton School (UPenn)", "University of Chicago (Economics)", "MIT Sloan", "NYU Stern", "Columbia Business School"],
    "United Kingdom": ["London School of Economics", "University of Oxford (Economics)", "University of Cambridge (Economics)", "Imperial College Business School", "Warwick Business School"],
    "Germany": ["Frankfurt School of Finance", "University of Mannheim", "Goethe University Frankfurt", "WHU – Otto Beisheim School", "LMU Munich (Economics)"],
    "Netherlands": ["Erasmus University Rotterdam", "Tilburg University", "University of Amsterdam (Economics)", "University of Groningen", "Maastricht University SBE"],
    "Switzerland": ["University of St. Gallen (HSG)", "University of Zurich (Economics)", "HEC Lausanne (UNIL)", "Geneva School of Economics", "University of Basel"],
    "Singapore": ["NUS (Economics)", "Singapore Management University", "NTU Nanyang Business School", "SIM Global Education", "ESSEC Asia-Pacific"],
    "Canada": ["University of Toronto (Economics)", "UBC Vancouver School of Economics", "McGill University", "Queen's University", "Western University (Ivey)"],
  },
  "Architecture & Urban Design": {
    "United Kingdom": ["The Bartlett (UCL)", "Architectural Association (AA London)", "University of Cambridge (Architecture)", "Manchester School of Architecture", "University of Sheffield"],
    "United States": ["MIT (Architecture)", "Harvard GSD", "Columbia GSAPP", "Cornell AAP", "SCI-Arc (Los Angeles)"],
    "Netherlands": ["TU Delft (Architecture)", "Eindhoven University of Technology", "Academy of Architecture Amsterdam", "University of Groningen", "Rotterdam Academy of Architecture"],
    "Germany": ["TU Munich (Architecture)", "TU Berlin", "RWTH Aachen", "Bauhaus-Universität Weimar", "University of Stuttgart"],
    "Italy": ["Politecnico di Milano (Architecture)", "Politecnico di Torino", "IUAV Venice", "Sapienza University of Rome", "University of Florence"],
    "Switzerland": ["ETH Zurich (Architecture)", "EPFL", "Accademia di architettura Mendrisio", "ZHAW", "HSLU Lucerne"],
    "Singapore": ["NUS (Architecture)", "Singapore University of Technology and Design", "NTU (Art, Design & Media)", "SIT", "LASALLE College of the Arts"],
  },
  "Pharmacy & Biomedical Sciences": {
    "United Kingdom": ["UCL School of Pharmacy", "University of Nottingham", "King's College London", "University of Manchester", "University of Bath"],
    "United States": ["UNC Chapel Hill (Eshelman)", "University of Michigan", "UCSF School of Pharmacy", "Johns Hopkins (Biomedical)", "Purdue University"],
    "Netherlands": ["Utrecht University (Pharmacy)", "Leiden University (LACDR)", "University of Groningen", "Radboud University", "VU Amsterdam"],
    "Germany": ["LMU Munich (Pharmacy)", "Heidelberg University", "Freie Universität Berlin", "University of Tübingen", "Goethe University Frankfurt"],
    "Sweden": ["Uppsala University (Pharmacy)", "Karolinska Institute", "University of Gothenburg", "Lund University", "Umeå University"],
    "Australia": ["Monash University (Pharmacy — QS #1)", "University of Sydney", "University of Queensland", "UNSW Sydney", "RMIT University"],
    "Canada": ["University of Toronto (Leslie Dan)", "UBC Pharmaceutical Sciences", "University of Alberta", "McGill University", "University of Waterloo"],
  },
  "Communication & Media Studies": {
    "United States": ["USC Annenberg", "Northwestern (Medill)", "Columbia Journalism School", "NYU (Media, Culture & Comm)", "Syracuse (Newhouse)"],
    "United Kingdom": ["London School of Economics (Media)", "Goldsmiths (University of London)", "Cardiff University (JOMEC)", "University of Leeds", "City, University of London"],
    "Netherlands": ["University of Amsterdam (Media Studies — QS top)", "Erasmus University Rotterdam", "VU Amsterdam", "Utrecht University", "Radboud University"],
    "Germany": ["Freie Universität Berlin", "LMU Munich (Communication)", "University of Hamburg", "University of Mannheim", "Hochschule für Medien Stuttgart"],
    "Australia": ["University of Melbourne", "Queensland University of Technology", "University of Sydney", "RMIT University", "Monash University"],
    "Singapore": ["NTU Wee Kim Wee School", "NUS (Communications & New Media)", "Singapore Management University", "SIM Global", "LASALLE College of the Arts"],
    "Canada": ["University of Toronto", "Carleton University (Journalism)", "UBC (Journalism)", "Toronto Metropolitan University", "Concordia University"],
  },
  "International Relations & Global Affairs": {
    "United States": ["Georgetown (SFS)", "Harvard Kennedy School", "Johns Hopkins SAIS", "Columbia SIPA", "Tufts (Fletcher School)"],
    "United Kingdom": ["London School of Economics (IR)", "University of Oxford (DPIR)", "King's College London (War Studies)", "University of Cambridge (POLIS)", "SOAS University of London"],
    "France": ["Sciences Po Paris", "Sorbonne University", "Sciences Po Lyon", "American University of Paris", "INALCO"],
    "Netherlands": ["Leiden University (International Studies)", "University of Amsterdam", "University of Groningen", "Erasmus University Rotterdam", "Maastricht University"],
    "Switzerland": ["Geneva Graduate Institute (IHEID)", "University of Geneva", "University of Zurich", "University of St. Gallen (International Affairs)", "University of Basel"],
    "Singapore": ["NUS (Lee Kuan Yew School)", "NTU (RSIS)", "Singapore Management University", "SIM Global", "Yale-NUS legacy programs (NUS College)"],
    "Canada": ["University of Toronto (Munk School)", "UBC (Political Science)", "McGill University", "Carleton (NPSIA)", "University of Ottawa (GSPIA)"],
  },
  "Cybersecurity & Network Engineering": {
    "United States": ["Carnegie Mellon (INI/CyLab)", "Georgia Tech", "MIT", "UC Berkeley", "Purdue University (CERIAS)"],
    "United Kingdom": ["University of Oxford (Cyber Security)", "Royal Holloway (Information Security)", "University of Edinburgh", "Lancaster University", "University of Southampton"],
    "Germany": ["Saarland University (CISPA)", "TU Darmstadt", "Ruhr University Bochum", "TU Munich", "Karlsruhe Institute of Technology"],
    "Netherlands": ["TU Delft", "University of Twente", "Radboud University (Digital Security)", "TU Eindhoven", "Vrije Universiteit Amsterdam"],
    "Switzerland": ["ETH Zurich", "EPFL", "University of Lausanne", "Bern University of Applied Sciences", "ZHAW"],
    "Australia": ["UNSW Sydney (UNSW Canberra Cyber)", "University of Melbourne", "Monash University", "Deakin University", "Edith Cowan University"],
    "Singapore": ["NUS (Computing)", "NTU", "Singapore Institute of Technology", "Singapore Management University", "SUTD"],
  },
  "Game Design & Interactive Media": {
    "United States": ["USC (Interactive Media & Games)", "NYU Game Center", "DigiPen Institute", "Carnegie Mellon (ETC)", "University of Utah (EAE)"],
    "United Kingdom": ["Abertay University (Dundee)", "University of the Arts London", "Falmouth University", "Staffordshire University", "Goldsmiths"],
    "Canada": ["Sheridan College", "Vancouver Film School", "University of British Columbia", "OCAD University", "Champlain College (Montreal)"],
    "Netherlands": ["Breda University (IGAD)", "HKU University of the Arts Utrecht", "Saxion University", "TU Delft", "Amsterdam University of Applied Sciences"],
    "Germany": ["Cologne Game Lab (TH Köln)", "HTW Berlin", "Mediadesign Hochschule", "Hochschule Darmstadt", "Games Academy Berlin"],
    "Japan": ["Tokyo Polytechnic University", "Digital Hollywood University", "Ritsumeikan University", "Tokyo University of Technology", "Vantan Game Academy"],
    "Sweden": ["Uppsala University (Campus Gotland)", "Södertörn University", "University of Skövde", "Luleå University of Technology", "Futuregames Stockholm"],
  },
  "Nursing & Allied Health": {
    "United States": ["University of Pennsylvania (Nursing — QS #1)", "Johns Hopkins School of Nursing", "Duke University", "University of Washington", "Emory University"],
    "United Kingdom": ["King's College London (Nightingale)", "University of Manchester", "University of Edinburgh", "University of Southampton", "Cardiff University"],
    "Australia": ["University of Technology Sydney", "University of Sydney", "Monash University", "Griffith University", "Deakin University"],
    "Canada": ["University of Toronto (Bloomberg)", "University of Alberta", "UBC School of Nursing", "McMaster University", "McGill (Ingram School)"],
    "Netherlands": ["Utrecht University (Clinical Health Sciences)", "Hanze UAS Groningen", "HU Utrecht", "Fontys University", "Amsterdam UMC programs"],
    "Sweden": ["Karolinska Institute", "University of Gothenburg", "Uppsala University", "Lund University", "Linköping University"],
    "Ireland": ["Trinity College Dublin", "University College Dublin", "University College Cork", "University of Galway", "RCSI Dublin"],
  },
  "Marketing & Advertising": {
    "United States": ["Northwestern (Kellogg/Medill IMC)", "NYU Stern", "University of Texas at Austin", "Michigan Ross", "Columbia Business School"],
    "United Kingdom": ["University of Bath", "Warwick Business School", "Lancaster University", "University of Leeds", "Cass/Bayes Business School"],
    "France": ["HEC Paris", "ESSEC", "ESCP Business School", "EM Lyon", "Audencia Nantes"],
    "Netherlands": ["Erasmus University Rotterdam", "University of Amsterdam", "Tilburg University", "University of Groningen", "Maastricht University"],
    "Australia": ["University of Melbourne", "UNSW Sydney", "Monash University", "University of Sydney", "QUT Brisbane"],
    "Spain": ["ESADE Barcelona", "IE University Madrid", "IESE Business School", "Universidad de Navarra", "EAE Business School"],
    "Singapore": ["NUS Business School", "NTU Nanyang", "Singapore Management University", "ESSEC Asia-Pacific", "Curtin Singapore"],
  },
  "Linguistics & Translation": {
    "United States": ["MIT (Linguistics — QS #1)", "Stanford University", "UMass Amherst", "UC Berkeley", "Georgetown University"],
    "United Kingdom": ["University of Edinburgh (Linguistics)", "University of Cambridge", "University of Oxford", "UCL", "SOAS University of London"],
    "Netherlands": ["University of Amsterdam", "Leiden University (LUCL)", "Utrecht University (UiL-OTS)", "Radboud University (MPI Nijmegen)", "University of Groningen"],
    "Germany": ["University of Heidelberg (Translation)", "Johannes Gutenberg University Mainz (Germersheim)", "University of Leipzig", "LMU Munich", "University of Cologne"],
    "Switzerland": ["University of Geneva (FTI — top translation school)", "University of Zurich", "University of Bern", "University of Lausanne", "ZHAW Applied Linguistics"],
    "France": ["ESIT (Sorbonne Nouvelle)", "ISIT Paris", "Sorbonne University", "University of Strasbourg", "Aix-Marseille University"],
    "Spain": ["University of Granada (Translation)", "Autonomous University of Barcelona", "University of Salamanca", "Pompeu Fabra University", "Complutense Madrid"],
  },
  "Electrical & Electronics Engineering": {
    "United States": ["MIT", "Stanford University", "UC Berkeley", "Georgia Tech", "University of Illinois Urbana-Champaign"],
    "Germany": ["TU Munich", "RWTH Aachen", "KIT Karlsruhe", "TU Berlin", "TU Dresden"],
    "United Kingdom": ["Imperial College London", "University of Cambridge", "University of Manchester", "University of Southampton", "University of Leeds"],
    "Netherlands": ["TU Delft", "TU Eindhoven", "University of Twente", "TU Delft — Microelectronics", "Vrije Universiteit Amsterdam"],
    "South Korea": ["KAIST", "Seoul National University", "POSTECH", "Yonsei University", "Korea University"],
    "Sweden": ["KTH Royal Institute of Technology", "Chalmers University of Technology", "Lund University", "Uppsala University", "Linköping University"],
    "Switzerland": ["ETH Zurich", "EPFL", "ZHAW", "FHNW", "Bern University of Applied Sciences"],
  },
  "Artificial Intelligence & Robotics": {
    "United States": ["Carnegie Mellon University", "MIT (CSAIL)", "Stanford University (SAIL)", "UC Berkeley (BAIR)", "University of Washington"],
    "United Kingdom": ["University of Oxford", "University of Cambridge", "University of Edinburgh (Informatics)", "Imperial College London", "UCL"],
    "Canada": ["University of Toronto (Vector Institute)", "University of Montreal (MILA)", "University of Alberta (Amii)", "UBC", "McGill University"],
    "Switzerland": ["ETH Zurich (AI Center)", "EPFL", "IDSIA Lugano (USI/SUPSI)", "University of Zurich", "University of Geneva"],
    "Germany": ["TU Munich (MIRMI)", "Max Planck Institute programs (Tübingen)", "KIT Karlsruhe", "TU Darmstadt", "University of Freiburg"],
    "Singapore": ["NUS (AI Institute)", "NTU", "SUTD", "Singapore Management University", "A*STAR-affiliated programs"],
    "Netherlands": ["University of Amsterdam (ELLIS)", "TU Delft (Robotics)", "TU Eindhoven", "Radboud University", "University of Groningen"],
  },
  "Biotechnology & Genetic Engineering": {
    "United States": ["MIT (Biological Engineering)", "Harvard University", "Stanford University", "UCSF", "UC San Diego"],
    "United Kingdom": ["University of Cambridge", "University of Oxford", "Imperial College London", "University of Edinburgh", "University of Manchester"],
    "Switzerland": ["ETH Zurich (D-BSSE Basel)", "EPFL", "University of Zurich", "University of Basel (Biozentrum)", "University of Bern"],
    "Denmark": ["Technical University of Denmark (DTU)", "University of Copenhagen", "Aarhus University", "Aalborg University", "University of Southern Denmark"],
    "Netherlands": ["Wageningen University", "TU Delft (Biotechnology)", "Utrecht University", "Leiden University", "University of Groningen"],
    "Germany": ["Heidelberg University", "TU Munich", "LMU Munich", "University of Tübingen", "RWTH Aachen"],
    "Australia": ["University of Queensland (AIBN)", "University of Melbourne", "Monash University", "UNSW Sydney", "Australian National University"],
  },
  "Dentistry & Oral Health": {
    "United Kingdom": ["King's College London (QS #1 Dentistry)", "UCL Eastman Dental Institute", "University of Manchester", "Cardiff University", "University of Birmingham"],
    "United States": ["University of Michigan", "Harvard School of Dental Medicine", "UNC Chapel Hill (Adams)", "University of Washington", "UCSF"],
    "Sweden": ["University of Gothenburg (Sahlgrenska)", "Karolinska Institute", "Malmö University", "Umeå University", "Uppsala University"],
    "Netherlands": ["ACTA Amsterdam (UvA/VU)", "Radboud University", "University of Groningen", "Utrecht University programs", "Maastricht University (adjacent)"],
    "Australia": ["University of Melbourne", "University of Sydney", "University of Queensland", "University of Adelaide", "Griffith University"],
    "Germany": ["Charité Berlin", "Heidelberg University", "LMU Munich", "University of Tübingen", "Goethe University Frankfurt"],
    "Hong Kong": ["University of Hong Kong (Faculty of Dentistry)", "HKU-affiliated Prince Philip Dental Hospital", "CUHK (adjacent programs)", "HK Polytechnic (hygiene)", "HKU SPACE"],
  },
  "Veterinary Medicine & Animal Sciences": {
    "United Kingdom": ["Royal Veterinary College London (QS #1)", "University of Edinburgh (Dick Vet)", "University of Cambridge", "University of Glasgow", "University of Liverpool"],
    "United States": ["UC Davis", "Cornell University", "Colorado State University", "Ohio State University", "Texas A&M University"],
    "Netherlands": ["Utrecht University (Faculty of Veterinary Medicine)", "Wageningen University (Animal Sciences)", "Van Hall Larenstein UAS", "Aeres UAS", "HAS green academy"],
    "Denmark": ["University of Copenhagen", "Aarhus University (Animal Science)", "Technical University of Denmark", "Aalborg University", "University of Southern Denmark"],
    "Austria": ["Vetmeduni Vienna", "University of Vienna (Biology)", "BOKU Vienna", "University of Graz", "University of Innsbruck"],
    "Australia": ["University of Sydney", "University of Melbourne", "University of Queensland", "Murdoch University", "Charles Sturt University"],
    "New Zealand": ["Massey University (Vet School)", "University of Auckland", "University of Otago", "Lincoln University", "Victoria University of Wellington"],
  },
  "Music & Performing Arts": {
    "United States": ["The Juilliard School", "Berklee College of Music", "Curtis Institute of Music", "New England Conservatory", "Manhattan School of Music"],
    "United Kingdom": ["Royal College of Music (QS #1)", "Royal Academy of Music", "Guildhall School of Music & Drama", "Royal Northern College of Music", "Trinity Laban"],
    "Austria": ["mdw — University of Music Vienna", "Mozarteum Salzburg", "Anton Bruckner University Linz", "JAM MUSIC LAB Vienna", "MUK Vienna"],
    "Germany": ["Hanns Eisler Berlin", "Hochschule für Musik München", "UdK Berlin", "HfMT Hamburg", "Hochschule für Musik Freiburg"],
    "France": ["Conservatoire de Paris (CNSMDP)", "École Normale de Musique", "Conservatoire de Lyon (CNSMDL)", "Pôle Sup' Paris", "American Conservatory Fontainebleau"],
    "Finland": ["Sibelius Academy (Uniarts Helsinki)", "Tampere University of Applied Sciences", "Metropolia UAS", "Turku UAS Arts Academy", "Centria UAS"],
    "Netherlands": ["Royal Conservatoire The Hague", "Conservatorium van Amsterdam", "Codarts Rotterdam", "Utrecht Conservatory (HKU)", "Prince Claus Conservatoire Groningen"],
  },
  "Sports Science & Physiotherapy": {
    "United Kingdom": ["Loughborough University (QS #1 Sport)", "University of Birmingham", "University of Bath", "Liverpool John Moores University", "University of Exeter"],
    "Australia": ["University of Queensland", "University of Sydney", "Deakin University", "Australian Catholic University", "Edith Cowan University"],
    "Netherlands": ["Vrije Universiteit Amsterdam (Human Movement)", "University of Groningen", "HAN UAS", "Fontys UAS", "The Hague UAS"],
    "Denmark": ["University of Copenhagen (NEXS)", "University of Southern Denmark", "Aarhus University", "Aalborg University", "Metropol UC"],
    "Germany": ["German Sport University Cologne", "TU Munich (Sport & Health)", "Leipzig University", "University of Freiburg", "Ruhr University Bochum"],
    "Norway": ["Norwegian School of Sport Sciences (NIH)", "NTNU Trondheim", "University of Agder", "UiT Tromsø", "Inland Norway UAS"],
    "Canada": ["University of British Columbia", "University of Toronto", "McMaster University", "University of Alberta", "Western University"],
  },
  "Hospitality & Tourism Management": {
    "Switzerland": ["EHL Hospitality Business School (QS #1)", "Les Roches Crans-Montana", "Glion Institute of Higher Education", "César Ritz Colleges", "Swiss Hotel Management School"],
    "United States": ["Cornell Nolan School of Hotel Administration", "UNLV (Harrah College)", "University of Central Florida (Rosen)", "Michigan State (Broad)", "NYU (Tisch Center)"],
    "Netherlands": ["Hotelschool The Hague", "Breda University of Applied Sciences", "NHL Stenden (Leeuwarden)", "Saxion UAS", "Zuyd UAS Maastricht"],
    "Hong Kong": ["Hong Kong Polytechnic University (SHTM)", "Chinese University of Hong Kong", "HKU (adjacent programs)", "Technological and Higher Education Institute", "HK PolyU SPEED"],
    "Spain": ["Les Roches Marbella", "IE University (Tourism)", "University of Girona", "CETT Barcelona (UB)", "Universidad Europea Madrid"],
    "United Arab Emirates": ["Emirates Academy of Hospitality Management", "Les Roches Abu Dhabi programs", "University of Dubai", "Middlesex University Dubai", "American University in the Emirates"],
    "Australia": ["Griffith University", "Blue Mountains International Hotel Management School", "University of Queensland", "William Angliss Institute", "ICMS Sydney"],
  },
  "Aerospace & Aeronautical Engineering": {
    "United States": ["MIT (AeroAstro)", "Caltech (GALCIT)", "Georgia Tech", "Purdue University", "University of Michigan"],
    "France": ["ISAE-SUPAERO Toulouse", "École Polytechnique", "ENAC Toulouse", "ESTACA", "IPSA Paris"],
    "Netherlands": ["TU Delft (Aerospace — EU #1)", "Inholland UAS (Aeronautical)", "Amsterdam UAS", "University of Twente", "TU Eindhoven"],
    "Germany": ["University of Stuttgart (Aerospace)", "TU Munich", "RWTH Aachen", "TU Berlin", "TU Braunschweig"],
    "United Kingdom": ["Imperial College London", "University of Bristol", "Cranfield University (postgrad)", "University of Bath", "University of Sheffield"],
    "Canada": ["University of Toronto (UTIAS)", "Carleton University", "Concordia University", "Toronto Metropolitan University", "McGill University"],
    "Australia": ["Monash University", "University of Sydney", "UNSW Sydney", "RMIT University", "University of Queensland"],
  },
  "Physics & Astronomy": {
    "United States": ["MIT", "Caltech", "Harvard University", "Princeton University", "UC Berkeley"],
    "United Kingdom": ["University of Cambridge (Cavendish)", "University of Oxford", "Imperial College London", "University of Edinburgh", "Durham University"],
    "Germany": ["LMU Munich", "Heidelberg University", "TU Munich", "University of Bonn", "Karlsruhe Institute of Technology"],
    "Switzerland": ["ETH Zurich", "EPFL", "University of Geneva (CERN proximity)", "University of Zurich", "University of Bern"],
    "Netherlands": ["Leiden University (Astronomy)", "University of Amsterdam", "Utrecht University", "University of Groningen (Kapteyn)", "Radboud University"],
    "Australia": ["Australian National University (Mt Stromlo)", "University of Melbourne", "University of Sydney", "Swinburne University (Astrophysics)", "University of Queensland"],
    "Canada": ["University of Toronto", "UBC", "McGill University", "University of Waterloo (Perimeter)", "University of Victoria"],
  },
};
