export const UNIVERSITIES_BY_COUNTRY: Record<string, Record<string, string[]>> = {
  "Computer Science & Software Engineering": {
    "United States": ["MIT", "Stanford University", "Carnegie Mellon University", "UC Berkeley", "University of Washington"],
    "Germany": ["TU Munich (TUM)", "RWTH Aachen University", "KIT Karlsruhe", "TU Berlin", "University of Stuttgart"],
    "United Kingdom": ["Imperial College London", "University of Cambridge", "University of Edinburgh", "UCL", "University of Manchester"],
    "Canada": ["University of Toronto", "University of Waterloo", "University of British Columbia", "McGill University", "University of Alberta"],
    "Netherlands": ["TU Delft", "University of Amsterdam", "Eindhoven University of Technology", "Vrije Universiteit Amsterdam", "University of Twente"],
    "Sweden": ["KTH Royal Institute of Technology", "Chalmers University of Technology", "Uppsala University", "Lund University", "Linköping University"],
    "Switzerland": ["ETH Zurich", "EPFL", "University of Zurich", "University of Basel", "University of Bern"],
    "Australia": ["University of Melbourne", "University of Sydney", "UNSW Sydney", "ANU", "Monash University"],
  },
  "Medicine & Health Sciences": {
    "United Kingdom": ["University of Oxford", "University of Cambridge", "Imperial College London", "King's College London", "University of Edinburgh"],
    "United States": ["Harvard Medical School", "Johns Hopkins University", "Stanford Medicine", "Mayo Clinic Alix School", "UCSF"],
    "Germany": ["Heidelberg University", "LMU Munich", "Charité — Universitätsmedizin Berlin", "TU Munich (Klinikum)", "University of Göttingen"],
    "Netherlands": ["Amsterdam UMC", "Erasmus MC", "Leiden University Medical Centre", "Maastricht University", "Radboud University"],
    "Australia": ["University of Melbourne", "University of Sydney", "Monash University", "University of Queensland", "ANU Medical School"],
    "Sweden": ["Karolinska Institute", "Uppsala University", "University of Gothenburg", "Lund University", "Umeå University"],
    "France": ["Paris Cité University (Paris Descartes)", "Sorbonne University", "University of Strasbourg", "Aix-Marseille University", "University of Bordeaux"],
  },
  "Business Administration & Management": {
    "United States": ["Wharton School (UPenn)", "Harvard Business School", "MIT Sloan", "Columbia Business School", "Booth School (UChicago)"],
    "United Kingdom": ["London Business School", "Oxford Saïd Business School", "Cambridge Judge Business School", "Imperial College Business School", "Warwick Business School"],
    "France": ["HEC Paris", "INSEAD (Fontainebleau)", "ESSEC Business School", "Sciences Po (Paris)", "EM Lyon Business School"],
    "Germany": ["WHU – Otto Beisheim School", "Mannheim Business School", "Frankfurt School of Finance", "HHL Leipzig Graduate School", "ESMT Berlin"],
    "Netherlands": ["Rotterdam School of Management (Erasmus)", "Amsterdam Business School", "Tilburg University", "University of Groningen", "Maastricht University SBE"],
    "Switzerland": ["IMD Business School (Lausanne)", "University of St. Gallen (HSG)", "Geneva School of Economics", "HEC Lausanne (UNIL)", "ZHAW School of Management"],
    "Singapore": ["NUS Business School", "NTU Nanyang Business School", "INSEAD Asia Campus", "SMU Lee Kong Chian School", "Singapore Management University"],
    "Canada": ["Ivey Business School (Western)", "Rotman School of Management (UofT)", "McGill Desautels Faculty", "Schulich School (York)", "HEC Montréal"],
  },
  "Law & Political Science": {
    "United Kingdom": ["University of Oxford (Law)", "University of Cambridge (Law)", "London School of Economics", "King's College London", "UCL Faculty of Laws"],
    "United States": ["Yale Law School", "Harvard Law School", "Columbia Law School", "NYU School of Law", "University of Chicago Law"],
    "Germany": ["Humboldt University Berlin", "LMU Munich (Law)", "University of Heidelberg", "University of Hamburg (Law)", "Freie Universität Berlin"],
    "Netherlands": ["Utrecht University (Law)", "Leiden University (Law)", "Maastricht University (Law)", "University of Amsterdam (Law)", "Tilburg Law School"],
    "Australia": ["University of Melbourne (Law)", "University of Sydney Law School", "ANU College of Law", "Monash Law School", "University of Queensland Law"],
    "France": ["Paris I Panthéon-Sorbonne", "Sciences Po Paris (Law)", "Université Paris II Assas", "University of Strasbourg (Law)", "University of Bordeaux (Law)"],
    "Canada": ["Osgoode Hall Law School (York)", "McGill Faculty of Law", "University of Toronto Law", "University of British Columbia Law", "Dalhousie Law School"],
  },
  "Mechanical & Civil Engineering": {
    "United States": ["MIT (Engineering)", "Stanford University", "Caltech", "Georgia Tech", "University of Michigan"],
    "Germany": ["TU Munich", "RWTH Aachen", "TU Berlin", "KIT Karlsruhe", "University of Stuttgart"],
    "United Kingdom": ["Imperial College London", "University of Cambridge", "University of Southampton", "University of Bristol", "University of Manchester"],
    "Netherlands": ["TU Delft", "Eindhoven University of Technology", "University of Twente", "Vrije Universiteit Amsterdam", "Wageningen University"],
    "Sweden": ["Chalmers University of Technology", "KTH Royal Institute of Technology", "Lund University", "Linköping University", "Uppsala University"],
    "Australia": ["University of Melbourne", "University of New South Wales", "Monash University", "University of Queensland", "University of Adelaide"],
    "Canada": ["University of Toronto", "University of Waterloo", "University of British Columbia", "McGill University", "University of Alberta"],
    "Switzerland": ["ETH Zurich", "EPFL", "University of Applied Sciences Lucerne", "ZHAW", "University of Bern"],
  },
  "Psychology & Social Sciences": {
    "United Kingdom": ["University of Cambridge", "University College London", "University of Edinburgh", "University of Exeter", "University of Bristol"],
    "United States": ["Harvard University (Psychology)", "Stanford University", "Yale University", "University of Michigan", "UC San Diego"],
    "Netherlands": ["University of Amsterdam", "Utrecht University", "Leiden University", "Tilburg University", "Radboud University Nijmegen"],
    "Germany": ["Heidelberg University", "LMU Munich", "Freie Universität Berlin", "Humboldt University Berlin", "University of Tübingen"],
    "Australia": ["University of Melbourne", "Australian National University", "University of Queensland", "University of Sydney", "Monash University"],
    "Sweden": ["Stockholm University", "Uppsala University", "Lund University", "Göteborg University", "Umeå University"],
    "Canada": ["University of Toronto", "McGill University", "University of British Columbia", "University of Waterloo", "University of Alberta"],
  },
  "Creative Arts & Graphic Design": {
    "United Kingdom": ["Royal College of Art (London)", "Goldsmiths (University of London)", "Central Saint Martins (UAL)", "University of the Arts London", "Falmouth University"],
    "United States": ["Rhode Island School of Design (RISD)", "Pratt Institute", "Parsons School of Design (The New School)", "ArtCenter College of Design", "SCAD (Savannah)"],
    "Netherlands": ["Design Academy Eindhoven", "Gerrit Rietveld Academie (Amsterdam)", "ArtEZ University of the Arts", "Royal Academy of Art The Hague", "HKU University of the Arts Utrecht"],
    "Germany": ["Bauhaus-Universität Weimar", "HfG Offenbach", "Berlin University of the Arts", "KISD Cologne", "Academy of Fine Arts Munich"],
    "Italy": ["Politecnico di Milano (Design)", "Istituto Marangoni (Milan)", "Accademia di Belle Arti Firenze", "NABA (Milan)", "ISIA Roma Design"],
    "Australia": ["RMIT University (Design)", "University of Technology Sydney", "Griffith College of Art", "University of Melbourne (Fine Arts)", "Queensland College of Art"],
    "Spain": ["IED Madrid (Istituto Europeo di Design)", "ELISAVA Barcelona", "Escola Massana (Barcelona)", "ESDESIGN Barcelona", "ESDIP Madrid"],
  },
  "Environmental Science & Sustainability": {
    "United Kingdom": ["University of Cambridge (Environmental)", "Imperial College London", "University of Edinburgh", "University of Leeds", "University of Southampton"],
    "United States": ["Yale School of the Environment", "UC Berkeley (Environmental Sciences)", "University of Michigan (SNRE)", "Duke Nicholas School", "Colorado State University"],
    "Germany": ["Leuphana University Lüneburg", "University of Freiburg (Environmental)", "TU Berlin (Environmental Planning)", "KIT (Environmental Engineering)", "University of Greifswald"],
    "Netherlands": ["Wageningen University (WUR)", "Utrecht University (Geosciences)", "Leiden University (CML)", "VU Amsterdam", "University of Groningen"],
    "Sweden": ["Stockholm University (Stockholm Resilience Centre)", "Lund University (LUCSUS)", "Uppsala University", "Linköping University", "Umeå University"],
    "Australia": ["Australian National University", "University of Melbourne", "UNSW Sydney (Environmental)", "James Cook University (Marine)", "Murdoch University"],
    "Canada": ["McGill University (Environment)", "UBC (Institute for Resources, Environment)", "Dalhousie University", "University of Waterloo", "University of Victoria"],
  },
  "Data Science & Statistics": {
    "United States": ["MIT (EECS / Statistics)", "Stanford (Statistics)", "Carnegie Mellon (Machine Learning)", "UC Berkeley (CDSS)", "University of Chicago (Statistics)"],
    "United Kingdom": ["University of Oxford (Statistics)", "University of Cambridge (MPhil Statistics)", "Imperial College London", "UCL (CS / Stats)", "University of Edinburgh"],
    "Germany": ["LMU Munich (Statistics / Data Science)", "TU Munich", "Humboldt University Berlin", "University of Mannheim", "RWTH Aachen"],
    "Netherlands": ["Eindhoven University of Technology", "TU Delft", "University of Amsterdam", "Utrecht University", "Vrije Universiteit Amsterdam"],
    "Switzerland": ["ETH Zurich (Data Science)", "EPFL (Computer and Communication Sciences)", "University of Zurich", "University of Lausanne", "University of Bern"],
    "Canada": ["University of Toronto", "University of Waterloo (Statistics)", "McGill University", "Simon Fraser University", "University of British Columbia"],
    "Australia": ["University of Melbourne", "ANU (Statistics)", "University of Sydney", "Monash University (Data Science)", "University of Queensland"],
    "Singapore": ["NUS (Statistics & Data Science)", "NTU (Data Science)", "Singapore Management University (IS)", "Singapore Institute of Technology", "SUTD"],
  },
  "Education & Teaching": {
    "United Kingdom": ["UCL Institute of Education", "University of Cambridge (Faculty of Education)", "University of Oxford (Dept of Education)", "University of Edinburgh", "University of Bristol"],
    "United States": ["Harvard Graduate School of Education", "Stanford Graduate School of Education", "Teachers College Columbia", "University of Michigan (Education)", "Vanderbilt Peabody College"],
    "Netherlands": ["Leiden University (Education Science)", "University of Amsterdam (Education)", "Utrecht University", "Radboud University Nijmegen", "VU Amsterdam"],
    "Germany": ["University of Munich (Teacher Training)", "Humboldt University Berlin (Education)", "University of Hamburg", "University of Cologne (Education)", "University of Frankfurt"],
    "Finland": ["University of Helsinki (Faculty of Educational Sciences)", "University of Tampere", "University of Jyväskylä", "University of Turku", "Åbo Akademi University"],
    "Australia": ["University of Melbourne (Graduate School of Education)", "Monash University (Education)", "University of Sydney", "Queensland University of Technology", "Australian Catholic University"],
    "Canada": ["OISE — University of Toronto", "University of British Columbia (Faculty of Education)", "McGill Faculty of Education", "York Faculty of Education", "University of Alberta (Education)"],
  },
};
